version: '3'
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
